name: flutter_midi_command_windows
description: FlutterMidiCommand for windows.
version: 0.0.1-dev.6
homepage: https://github.com/InvisibleWrench/FlutterMidiCommand

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command_platform_interface: ^0.4.0
  ffi: ^2.1.0
  win32: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  plugin:
    implements: flutter_midi_command
    platforms:
      windows:
        dartPluginClass: FlutterMidiCommandWindows
