name: flutter_midi_command_windows
description: FlutterMidiCommand for windows.
version: 0.2.0
homepage: https://github.com/InvisibleWrench/FlutterMidiCommand

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command_platform_interface: ^0.4.0
  ffi: ^2.1.0
  win32: ^5.5.0
  universal_ble: ^0.9.11
  device_manager: #^0.0.2
    git: 
      url: https://github.com/bojidartonchev/device_manager.git
      ref: c53f37f10b1286590e6487d8d344021a700ca04c # use PR #3

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  plugin:
    implements: flutter_midi_command
    platforms:
      windows:
        dartPluginClass: FlutterMidiCommandWindows
