name: flutter_midi_command_windows
description: FlutterMidiCommand for windows.
version: 0.0.1
homepage: https://github.com/InvisibleWrench/FlutterMidiCommand

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command_platform_interface: ^0.4.0
  win32: ^5.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  plugin:
    implements: flutter_midi_command
    platforms:
      windows:
        dartPluginClass: flutter_midi_command_windows
